apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - api-service.yaml
  - api-configmap.yaml
  - api-hpa.yaml
  - ingress.yaml
  - storage-pvc.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: yolo-api
  app.kubernetes.io/part-of: yolo-traffic-detection

# Variables that will be replaced in the resources
vars:
  - name: API_IMAGE
    objref:
      kind: Deployment
      name: yolo-api
      apiVersion: apps/v1
    fieldref:
      fieldpath: spec.template.spec.containers[0].image