apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo-api-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard  # Replace with your desired storage class