apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Common labels for all resources in this overlay
commonLabels:
  environment: dev

# Patches for resources
patchesStrategicMerge:
  - patch-api.yaml

# Image configuration
images:
  - name: ${API_IMAGE}
    newName: yolo-k8s-api
    newTag: latest