apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-api-config
data:
  API_DEBUG: "true"
  LOG_LEVEL: "DEBUG"
  MODEL_NAME: "yolov8n.pt"  # Use smaller model for dev